spring:
  application:
    name: modulith-app
  docker:
    compose:
      lifecycle-management: start_only

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: secret

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  modulith:
    events:
      republish-outstanding-events-on-restart: true
      externalization:
        enabled: true
#      jdbc:
#        schema-initialization:
#          enabled: true
