spring:
  application:
    name: modulith-app
  docker:
    compose:
      lifecycle-management: start_only

  datasource:
    driver-class-name: org.postgresql.Driver
    url:
      jdbc:postgresql://localhost:5432/mydatabase   # H2 DB 연결 주소 (In-Memory Mode)
    username: myuser        # H2 DB 접속 ID (사용자 지정)
    password: secret        # H2 DB 접속 PW (사용자 지정)

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create        # DB 초기화 전략 (none, create, create-drop, update, validate)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
